// <auto-generated />
namespace Topdf.api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Priya1232 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Priya1232));
        
        string IMigrationMetadata.Id
        {
            get { return "201703101138470_Priya1232"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
